### ISSUE TITLE
(依頼)chat-space挙動確認

### ISSUE THREAD

**Issue by mnboogaloo** [mnboogaloo/chat-space2#7]
＃IPアドレス
52.196.147.26

**Comment by mutorisa** [comment]
ご提出ありがとうございます！！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**[修正依頼箇所]**

### ○「Log in」「Sign up」「Edit Accoun」の文字の色を黒にしましょう。

[参考]
https://master.tech-camp.in/curriculums/4265

<img width="1310" alt="文字色" src="https://user-images.githubusercontent.com/65144927/83964666-74e17380-a8e9-11ea-96e7-85df1d1b3ef5.png">


### ○サイドバーの名前横のアイコンの位置を調整しましょう。

[参考]
https://master.tech-camp.in/curriculums/3944

<img width="1043" alt="アイコン" src="https://user-images.githubusercontent.com/65144927/83964708-b2460100-a8e9-11ea-806e-4d52133de197.png">


### ○グループの編集が可能なグループ編集ページに飛べるようにしましょう。

[参考]
https://master.tech-camp.in/curriculums/4049

現状以下の添付画像のように表示されてしまいます。
<img width="621" alt="スクリーンショット 2020-06-07 18 03 52" src="https://user-images.githubusercontent.com/65144927/83964740-f3d6ac00-a8e9-11ea-917d-fd89ef5f3bb5.png">


修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただきご提出をお願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by mnboogaloo** [comment]
上記３点修正しました。
よろしくお願いします。

**Comment by miyu-yamamoto** [comment]
西川さん、修正と再提出ありがとうございます！
前回指摘した箇所は全て問題なく修正されておりました◎

ただ、新たにもう一点修正をお願いしたい箇所があるので確認をお願いします。
[修正箇所]
**○ サイドバーの文字の下線を表示させなくしましょう**
<img width="229" alt="スクリーンショット 2020-06-07 13 57 59" src="https://user-images.githubusercontent.com/59544869/83991566-1b7c5180-a988-11ea-852e-9690a933ff61.png">

修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by mnboogaloo** [comment]
修正しました。
よろしくお願いします。

**Comment by mutorisa** [comment]
修正後、再度ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！！

⭐️今後実装に関するご質問がございましたら、メンターに相談いただきますようお願いします。
